## LAB 1

#### Experiment 1: Read different file formats using Python Libraries

Types of files:
- CSV (Comma Separated Values)
- JSON (JavaScript Object Notation)
- XML (eXtensible Markup Language)
- TXT (Text Files)
- XLSX (Microsoft Excel Open XML Spreadsheet)
- DOC (Microsoft Word Document)
- MAT (MATLAB Data File)
- HTM / HTML (Hypertext Markup Language)
- PKL (Python Pickle File)

#### Experiment 2: Download and clearn Iris Dataset

# Experiment 1: Read Different File Formats

In [ ]:
import pandas as pd

df = pd.read_csv('l1.data.csv')

In [3]:
df.sample(5)

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
425,0,0.971352,24,0,0.035803,1200.0,3,0,0,0,0.0
671,0,0.038258,68,0,0.009832,6000.0,12,0,0,0,0.0
191,0,1.095083,53,5,0.536704,3500.0,7,1,1,2,0.0
424,0,0.397703,38,0,0.416275,5750.0,6,0,1,0,2.0
497,0,0.193585,51,0,0.532755,3800.0,13,0,2,0,0.0

In [5]:
df.all()

SeriousDlqin2yrs                        False
RevolvingUtilizationOfUnsecuredLines    False
age                                      True
NumberOfTime30-59DaysPastDueNotWorse    False
DebtRatio                               False
MonthlyIncome                           False
NumberOfOpenCreditLinesAndLoans         False
NumberOfTimes90DaysLate                 False
NumberRealEstateLoansOrLines            False
NumberOfTime60-89DaysPastDueNotWorse    False
NumberOfDependents                      False
dtype: bool

In [ ]:
# find the na values in the dataset 
df.isnull().sum()

SeriousDlqin2yrs                          0
RevolvingUtilizationOfUnsecuredLines      0
age                                       0
NumberOfTime30-59DaysPastDueNotWorse      0
DebtRatio                                 0
MonthlyIncome                           136
NumberOfOpenCreditLinesAndLoans           0
NumberOfTimes90DaysLate                   0
NumberRealEstateLoansOrLines              0
NumberOfTime60-89DaysPastDueNotWorse      0
NumberOfDependents                       26
dtype: int64

# Experiment 2: Iris Dataset

In [7]:
iris_dataset = pd.read_csv('Iris.csv')

In [8]:
iris_dataset.sample(5)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
64,65,5.6,2.9,3.6,1.3,Iris-versicolor
137,138,6.4,3.1,5.5,1.8,Iris-virginica
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
10,11,5.4,3.7,1.5,0.2,Iris-setosa
62,63,6.0,2.2,4.0,1.0,Iris-versicolor