In [3]:
import pandas as pd

df = pd.read_csv("data.csv")

In [4]:
df.sample(10)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
8,2009-01-02,2009,NaN,603540.0,1680000,Single Family,Detached House,3,1,1039.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000,?,Detached House,3,2,1092.0,1.025953,East
0,2009-01-02,2009,Waterbury,111440.0,185000,Single Family,Detached House,3,3,996.0,1.025953,South
10,2009-01-03,2009,Bridgeport,122150.0,256500,Single Family,Detached House,3,1,926.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000,Two Family,Duplex,4,3,1241.0,1.025953,South
12,2009-01-03,2009,Bridgeport,103950.0,310000,Single Family,Detached House,3,2,997.0,1.025953,East
3,2009-01-02,2009,Bridgeport,4775276.0,272900,Single Family,Detached House,3,1,971.0,1.025953,East
6,2009-01-02,2009,Norwalk,571060.0,1000000,Single Family,Detached House,3,2,NaN,1.025953,South
9,2009-01-02,2009,Bridgeport,137901.0,245000,Single Family,Detached House,3,1,956.0,1.025953,West
11,2009-01-03,2009,Norwalk,NaN,1340000,Single Family,Detached House,3,1,936.0,1.025953,North

In [5]:
# Dataframe
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'London', 'Tokyo', 'Paris', 'Sydney']
})

In [ ]:
df.sample(3)  # Randomly sample 3 rows from the DataFrame

    Name  Age      City
4    Eva   45    Sydney
3  David   40     Paris
0  Alice   25  New York

In [10]:
df.loc[1:4] # Select rows by index label (rows 1 to 4)

      Name  Age    City
1      Bob   30  London
2  Charlie   35   Tokyo
3    David   40   Paris
4      Eva   45  Sydney

In [8]:
df.iloc[1:4]  # Select rows by index position (rows 1 to 3)

      Name  Age    City
1      Bob   30  London
2  Charlie   35   Tokyo
3    David   40   Paris

In [ ]:
7

3

4